import pandas as pd
import numpy as np
import ta

class FeatureEngineer:
    def __init__(self):
        pass

    def add_all_features(self, df):
        """
        Adds technical indicators to the dataframe.
        """
        df = df.copy()
        
        # Ensure correct types
        df['close'] = df['close'].astype(float)
        df['high'] = df['high'].astype(float)
        df['low'] = df['low'].astype(float)
        df['volume'] = df['volume'].astype(float)

        # 1. Trend Indicators
        # SMA
        df['sma_50'] = ta.trend.sma_indicator(df['close'], window=50)
        df['sma_200'] = ta.trend.sma_indicator(df['close'], window=200)
        # EMA
        df['ema_20'] = ta.trend.ema_indicator(df['close'], window=20)

        # 2. Momentum Indicators
        # RSI
        df['rsi'] = ta.momentum.rsi(df['close'], window=14)
        # MACD
        macd = ta.trend.MACD(df['close'])
        df['macd'] = macd.macd()
        df['macd_signal'] = macd.macd_signal()
        df['macd_diff'] = macd.macd_diff()

        # 3. Volatility Indicators
        # Bollinger Bands
        bb = ta.volatility.BollingerBands(df['close'], window=20, window_dev=2)
        df['bb_high'] = bb.bollinger_hband()
        df['bb_low'] = bb.bollinger_lband()
        df['bb_width'] = bb.bollinger_wband()
        # ATR
        df['atr'] = ta.volatility.average_true_range(df['high'], df['low'], df['close'], window=14)

        # 4. Volume Indicators
        # OBV
        df['obv'] = ta.volume.on_balance_volume(df['close'], df['volume'])

        # Drop NaN values generated by lookback windows
        df.dropna(inplace=True)
        
        return df

if __name__ == "__main__":
    # Test
    # Load dummy data or file
    try:
        df = pd.read_csv('../data/BTC_USDT_4h.csv') # Assuming data exists from data_fetcher
        fe = FeatureEngineer()
        df_features = fe.add_all_features(df)
        print(df_features.tail())
        print("Features added successfully.")
    except Exception as e:
        print(f"Error: {e}")
